name: generate wins

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: run script
        run: |
          python wins.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generate wins for $(date +%Y)"
          git push
